language: go
go:
- 1.1
- 1.2
- 1.3
- release

before_install:
- cd $HOME
- mv $HOME/gopath/src/github.com/CPSSD $HOME/gopath/src/github.com/cpssd
- TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/cpssd/paranoid
- cd $TRAVIS_BUILD_DIR
