// Code generated by protoc-gen-go.
// source: paranoidnetwork/paranoid.proto
// DO NOT EDIT!

/*
Package paranoid is a generated protocol buffer package.

It is generated from these files:
	paranoidnetwork/paranoid.proto

It has these top-level messages:
	EmptyMessage
	PingRequest
	CreatRequest
	WriteRequest
	WriteResponse
	LinkRequest
	UnlinkRequest
	RenameRequest
	TruncateRequest
	UtimesRequest
	ChmodRequest
	MkdirRequest
	RmdirRequest
*/
package paranoid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PingRequest struct {
	Ip         string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port       string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	CommonName string `protobuf:"bytes,3,opt,name=common_name" json:"common_name,omitempty"`
}

func (m *PingRequest) Reset()                    { *m = PingRequest{} }
func (m *PingRequest) String() string            { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()               {}
func (*PingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreatRequest struct {
	Path        string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Permissions uint32 `protobuf:"varint,2,opt,name=permissions" json:"permissions,omitempty"`
}

func (m *CreatRequest) Reset()                    { *m = CreatRequest{} }
func (m *CreatRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatRequest) ProtoMessage()               {}
func (*CreatRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type WriteRequest struct {
	Path   string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Offset uint64 `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	Length uint64 `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
}

func (m *WriteRequest) Reset()                    { *m = WriteRequest{} }
func (m *WriteRequest) String() string            { return proto.CompactTextString(m) }
func (*WriteRequest) ProtoMessage()               {}
func (*WriteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type WriteResponse struct {
	BytesWritten uint64 `protobuf:"varint,1,opt,name=bytes_written" json:"bytes_written,omitempty"`
}

func (m *WriteResponse) Reset()                    { *m = WriteResponse{} }
func (m *WriteResponse) String() string            { return proto.CompactTextString(m) }
func (*WriteResponse) ProtoMessage()               {}
func (*WriteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type LinkRequest struct {
	OldPath string `protobuf:"bytes,1,opt,name=old_path" json:"old_path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=new_path" json:"new_path,omitempty"`
}

func (m *LinkRequest) Reset()                    { *m = LinkRequest{} }
func (m *LinkRequest) String() string            { return proto.CompactTextString(m) }
func (*LinkRequest) ProtoMessage()               {}
func (*LinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type UnlinkRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *UnlinkRequest) Reset()                    { *m = UnlinkRequest{} }
func (m *UnlinkRequest) String() string            { return proto.CompactTextString(m) }
func (*UnlinkRequest) ProtoMessage()               {}
func (*UnlinkRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RenameRequest struct {
	OldPath string `protobuf:"bytes,1,opt,name=old_path" json:"old_path,omitempty"`
	NewPath string `protobuf:"bytes,2,opt,name=new_path" json:"new_path,omitempty"`
}

func (m *RenameRequest) Reset()                    { *m = RenameRequest{} }
func (m *RenameRequest) String() string            { return proto.CompactTextString(m) }
func (*RenameRequest) ProtoMessage()               {}
func (*RenameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type TruncateRequest struct {
	Path   string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Length uint64 `protobuf:"varint,2,opt,name=length" json:"length,omitempty"`
}

func (m *TruncateRequest) Reset()                    { *m = TruncateRequest{} }
func (m *TruncateRequest) String() string            { return proto.CompactTextString(m) }
func (*TruncateRequest) ProtoMessage()               {}
func (*TruncateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type UtimesRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *UtimesRequest) Reset()                    { *m = UtimesRequest{} }
func (m *UtimesRequest) String() string            { return proto.CompactTextString(m) }
func (*UtimesRequest) ProtoMessage()               {}
func (*UtimesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type ChmodRequest struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
	Mode uint32 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *ChmodRequest) Reset()                    { *m = ChmodRequest{} }
func (m *ChmodRequest) String() string            { return proto.CompactTextString(m) }
func (*ChmodRequest) ProtoMessage()               {}
func (*ChmodRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type MkdirRequest struct {
	Directory string `protobuf:"bytes,1,opt,name=directory" json:"directory,omitempty"`
	Mode      uint32 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *MkdirRequest) Reset()                    { *m = MkdirRequest{} }
func (m *MkdirRequest) String() string            { return proto.CompactTextString(m) }
func (*MkdirRequest) ProtoMessage()               {}
func (*MkdirRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type RmdirRequest struct {
	Directory string `protobuf:"bytes,1,opt,name=directory" json:"directory,omitempty"`
}

func (m *RmdirRequest) Reset()                    { *m = RmdirRequest{} }
func (m *RmdirRequest) String() string            { return proto.CompactTextString(m) }
func (*RmdirRequest) ProtoMessage()               {}
func (*RmdirRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "paranoid.EmptyMessage")
	proto.RegisterType((*PingRequest)(nil), "paranoid.PingRequest")
	proto.RegisterType((*CreatRequest)(nil), "paranoid.CreatRequest")
	proto.RegisterType((*WriteRequest)(nil), "paranoid.WriteRequest")
	proto.RegisterType((*WriteResponse)(nil), "paranoid.WriteResponse")
	proto.RegisterType((*LinkRequest)(nil), "paranoid.LinkRequest")
	proto.RegisterType((*UnlinkRequest)(nil), "paranoid.UnlinkRequest")
	proto.RegisterType((*RenameRequest)(nil), "paranoid.RenameRequest")
	proto.RegisterType((*TruncateRequest)(nil), "paranoid.TruncateRequest")
	proto.RegisterType((*UtimesRequest)(nil), "paranoid.UtimesRequest")
	proto.RegisterType((*ChmodRequest)(nil), "paranoid.ChmodRequest")
	proto.RegisterType((*MkdirRequest)(nil), "paranoid.MkdirRequest")
	proto.RegisterType((*RmdirRequest)(nil), "paranoid.RmdirRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for ParanoidNetwork service

type ParanoidNetworkClient interface {
	// Used for health checking and discovery. Sends the IP and port of the
	// PFSD instance running on the client.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// Filesystem calls
	Creat(ctx context.Context, in *CreatRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error)
	Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Utimes(ctx context.Context, in *UtimesRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Rmdir(ctx context.Context, in *RmdirRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type paranoidNetworkClient struct {
	cc *grpc.ClientConn
}

func NewParanoidNetworkClient(cc *grpc.ClientConn) ParanoidNetworkClient {
	return &paranoidNetworkClient{cc}
}

func (c *paranoidNetworkClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Creat(ctx context.Context, in *CreatRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Creat", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Write(ctx context.Context, in *WriteRequest, opts ...grpc.CallOption) (*WriteResponse, error) {
	out := new(WriteResponse)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Link(ctx context.Context, in *LinkRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Link", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Unlink(ctx context.Context, in *UnlinkRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Unlink", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Rename", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Truncate(ctx context.Context, in *TruncateRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Truncate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Utimes(ctx context.Context, in *UtimesRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Utimes", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Chmod(ctx context.Context, in *ChmodRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Chmod", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Mkdir(ctx context.Context, in *MkdirRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Mkdir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) Rmdir(ctx context.Context, in *RmdirRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Rmdir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ParanoidNetwork service

type ParanoidNetworkServer interface {
	// Used for health checking and discovery. Sends the IP and port of the
	// PFSD instance running on the client.
	Ping(context.Context, *PingRequest) (*EmptyMessage, error)
	// Filesystem calls
	Creat(context.Context, *CreatRequest) (*EmptyMessage, error)
	Write(context.Context, *WriteRequest) (*WriteResponse, error)
	Link(context.Context, *LinkRequest) (*EmptyMessage, error)
	Unlink(context.Context, *UnlinkRequest) (*EmptyMessage, error)
	Rename(context.Context, *RenameRequest) (*EmptyMessage, error)
	Truncate(context.Context, *TruncateRequest) (*EmptyMessage, error)
	Utimes(context.Context, *UtimesRequest) (*EmptyMessage, error)
	Chmod(context.Context, *ChmodRequest) (*EmptyMessage, error)
	Mkdir(context.Context, *MkdirRequest) (*EmptyMessage, error)
	Rmdir(context.Context, *RmdirRequest) (*EmptyMessage, error)
}

func RegisterParanoidNetworkServer(s *grpc.Server, srv ParanoidNetworkServer) {
	s.RegisterService(&_ParanoidNetwork_serviceDesc, srv)
}

func _ParanoidNetwork_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Ping(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Creat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CreatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Creat(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(WriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Write(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(LinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Link(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Unlink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UnlinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Unlink(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Rename(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Truncate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(TruncateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Truncate(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Utimes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(UtimesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Utimes(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Chmod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ChmodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Chmod(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Mkdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(MkdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Mkdir(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ParanoidNetwork_Rmdir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RmdirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ParanoidNetworkServer).Rmdir(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _ParanoidNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paranoid.ParanoidNetwork",
	HandlerType: (*ParanoidNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ParanoidNetwork_Ping_Handler,
		},
		{
			MethodName: "Creat",
			Handler:    _ParanoidNetwork_Creat_Handler,
		},
		{
			MethodName: "Write",
			Handler:    _ParanoidNetwork_Write_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _ParanoidNetwork_Link_Handler,
		},
		{
			MethodName: "Unlink",
			Handler:    _ParanoidNetwork_Unlink_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _ParanoidNetwork_Rename_Handler,
		},
		{
			MethodName: "Truncate",
			Handler:    _ParanoidNetwork_Truncate_Handler,
		},
		{
			MethodName: "Utimes",
			Handler:    _ParanoidNetwork_Utimes_Handler,
		},
		{
			MethodName: "Chmod",
			Handler:    _ParanoidNetwork_Chmod_Handler,
		},
		{
			MethodName: "Mkdir",
			Handler:    _ParanoidNetwork_Mkdir_Handler,
		},
		{
			MethodName: "Rmdir",
			Handler:    _ParanoidNetwork_Rmdir_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x94, 0x5f, 0x6b, 0x13, 0x41,
	0x10, 0xc0, 0x6d, 0xbc, 0x84, 0x74, 0x72, 0xd7, 0xea, 0x4a, 0x35, 0x16, 0x14, 0xbd, 0x07, 0x11,
	0x85, 0x06, 0xed, 0x83, 0xf8, 0x07, 0x7c, 0x10, 0x5f, 0xc4, 0x4a, 0x09, 0x8a, 0x8f, 0x61, 0x9b,
	0x9b, 0xa6, 0x4b, 0xb2, 0xbb, 0xe7, 0xee, 0x96, 0x90, 0xcf, 0xe3, 0x17, 0x75, 0x77, 0x2f, 0x67,
	0xe6, 0xb4, 0xb9, 0xea, 0xe3, 0x4c, 0xe6, 0x37, 0x33, 0x7b, 0xf3, 0x23, 0xf0, 0xb0, 0xe4, 0x86,
	0x2b, 0x2d, 0x0a, 0x85, 0x6e, 0xa9, 0xcd, 0x7c, 0x54, 0xc7, 0x47, 0xa5, 0xd1, 0x4e, 0xb3, 0x7e,
	0x1d, 0xe7, 0x7b, 0x90, 0x7e, 0x94, 0xa5, 0x5b, 0x9d, 0xa0, 0xb5, 0x7c, 0x86, 0xf9, 0x3b, 0x18,
	0x9c, 0x0a, 0x35, 0x1b, 0xe3, 0x8f, 0x4b, 0xb4, 0x8e, 0x01, 0x74, 0x44, 0x39, 0xdc, 0x79, 0xb4,
	0xf3, 0x74, 0x97, 0xa5, 0x90, 0x94, 0xda, 0xb8, 0x61, 0x27, 0x46, 0x77, 0x60, 0x30, 0xd5, 0x52,
	0x6a, 0x35, 0x51, 0x5c, 0xe2, 0xf0, 0x66, 0x48, 0xe6, 0x2f, 0x20, 0xfd, 0x60, 0x90, 0xbb, 0x1a,
	0x0f, 0x08, 0x77, 0x17, 0xeb, 0x06, 0x1e, 0x29, 0xd1, 0x48, 0x61, 0xad, 0xd0, 0xca, 0xc6, 0x3e,
	0x59, 0xfe, 0x09, 0xd2, 0xef, 0x46, 0x38, 0xbc, 0x1a, 0xf1, 0x51, 0xc1, 0x1d, 0x8f, 0xb5, 0x29,
	0xdb, 0x83, 0x9e, 0x3e, 0x3f, 0xb7, 0xe8, 0xe2, 0xb8, 0x24, 0xc4, 0x0b, 0x54, 0x33, 0x5f, 0x9d,
	0x84, 0x38, 0x7f, 0x02, 0xd9, 0xba, 0x97, 0x2d, 0xfd, 0x04, 0x64, 0x07, 0x90, 0x9d, 0xad, 0x1c,
	0xda, 0xc9, 0xd2, 0xa7, 0x1d, 0xaa, 0xd8, 0x35, 0xf1, 0x6b, 0x0e, 0x3e, 0x0b, 0x35, 0xaf, 0x47,
	0xde, 0x82, 0xbe, 0x5e, 0x14, 0x13, 0x32, 0xd6, 0x67, 0x14, 0x2e, 0xab, 0x4c, 0x7c, 0x6e, 0xfe,
	0x00, 0xb2, 0x6f, 0x6a, 0x41, 0xa0, 0xc6, 0x9e, 0xf9, 0x31, 0x64, 0x63, 0x0c, 0x1f, 0xe2, 0x7f,
	0x7a, 0x8e, 0x60, 0xff, 0xab, 0xb9, 0x54, 0x53, 0xbe, 0xed, 0xf5, 0x9b, 0xf7, 0x75, 0xe2, 0xde,
	0xcf, 0xfd, 0x12, 0x4e, 0x48, 0xb4, 0xff, 0xf0, 0xb1, 0xf2, 0x67, 0xfe, 0x16, 0x17, 0x52, 0x17,
	0x5b, 0x6b, 0xfd, 0x6f, 0xb8, 0x3e, 0xc2, 0x08, 0xd2, 0x93, 0x79, 0x21, 0x4c, 0x5d, 0x7b, 0x1b,
	0x76, 0x7d, 0x84, 0x53, 0xa7, 0xcd, 0xea, 0x4a, 0xe0, 0x31, 0xa4, 0x63, 0xd9, 0x0a, 0xbc, 0xfc,
	0xd9, 0x85, 0xfd, 0xd3, 0xb5, 0x66, 0x5f, 0x2a, 0x0d, 0xd9, 0x2b, 0x48, 0x82, 0x5d, 0xec, 0xe0,
	0xe8, 0xb7, 0x90, 0xc4, 0xb6, 0xc3, 0xbb, 0x9b, 0x74, 0x43, 0xca, 0x1b, 0xec, 0x35, 0x74, 0xa3,
	0x58, 0x8c, 0x94, 0x50, 0xd3, 0x5a, 0xd0, 0x37, 0xd0, 0x8d, 0x52, 0x50, 0x94, 0x1a, 0x77, 0x78,
	0xef, 0xaf, 0x7c, 0x65, 0x8f, 0x67, 0xfd, 0xbe, 0x41, 0x14, 0xba, 0x2f, 0x11, 0xa7, 0x65, 0xe8,
	0x5b, 0xe8, 0x55, 0xba, 0x30, 0xd2, 0xbd, 0x21, 0x50, 0x3b, 0x5c, 0xc9, 0x44, 0xe1, 0x86, 0x5e,
	0x2d, 0xf0, 0x7b, 0xe8, 0xd7, 0x52, 0xb1, 0xfb, 0x9b, 0xaa, 0x3f, 0x44, 0xbb, 0x66, 0xf5, 0x28,
	0x59, 0x63, 0x75, 0xaa, 0xdd, 0x35, 0x77, 0x0a, 0xd2, 0x35, 0xee, 0x44, 0x2c, 0x6c, 0x47, 0xa3,
	0x83, 0x14, 0xa5, 0x52, 0xb6, 0xa3, 0xd1, 0x46, 0x8a, 0x52, 0x3d, 0xb7, 0xa3, 0x67, 0xbd, 0xf8,
	0x87, 0x78, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x02, 0x48, 0x6c, 0x32, 0x05, 0x00, 0x00,
}
