// Code generated by protoc-gen-go.
// source: paranoidnetwork/paranoid.proto
// DO NOT EDIT!

/*
Package paranoid is a generated protocol buffer package.

It is generated from these files:
	paranoidnetwork/paranoid.proto

It has these top-level messages:
	EmptyMessage
	Node
	JoinClusterRequest
	NewGenerationRequest
	NewGenerationResponse
	KeyPiece
*/
package paranoid

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Node struct {
	Ip         string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port       string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	CommonName string `protobuf:"bytes,3,opt,name=common_name,json=commonName" json:"common_name,omitempty"`
	Uuid       string `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type JoinClusterRequest struct {
	Ip           string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port         string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	CommonName   string `protobuf:"bytes,3,opt,name=common_name,json=commonName" json:"common_name,omitempty"`
	Uuid         string `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
	PoolPassword string `protobuf:"bytes,5,opt,name=pool_password,json=poolPassword" json:"pool_password,omitempty"`
}

func (m *JoinClusterRequest) Reset()                    { *m = JoinClusterRequest{} }
func (m *JoinClusterRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinClusterRequest) ProtoMessage()               {}
func (*JoinClusterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type NewGenerationRequest struct {
	RequestingNode *Node `protobuf:"bytes,1,opt,name=requesting_node,json=requestingNode" json:"requesting_node,omitempty"`
}

func (m *NewGenerationRequest) Reset()                    { *m = NewGenerationRequest{} }
func (m *NewGenerationRequest) String() string            { return proto.CompactTextString(m) }
func (*NewGenerationRequest) ProtoMessage()               {}
func (*NewGenerationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *NewGenerationRequest) GetRequestingNode() *Node {
	if m != nil {
		return m.RequestingNode
	}
	return nil
}

type NewGenerationResponse struct {
	GenerationNumber int64   `protobuf:"varint,1,opt,name=generation_number,json=generationNumber" json:"generation_number,omitempty"`
	Peers            []*Node `protobuf:"bytes,2,rep,name=peers" json:"peers,omitempty"`
}

func (m *NewGenerationResponse) Reset()                    { *m = NewGenerationResponse{} }
func (m *NewGenerationResponse) String() string            { return proto.CompactTextString(m) }
func (*NewGenerationResponse) ProtoMessage()               {}
func (*NewGenerationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NewGenerationResponse) GetPeers() []*Node {
	if m != nil {
		return m.Peers
	}
	return nil
}

type KeyPiece struct {
	Data              []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	ParentFingerprint []byte `protobuf:"bytes,2,opt,name=parent_fingerprint,json=parentFingerprint,proto3" json:"parent_fingerprint,omitempty"`
	Prime             []byte `protobuf:"bytes,3,opt,name=prime,proto3" json:"prime,omitempty"`
	Seq               int64  `protobuf:"varint,4,opt,name=seq" json:"seq,omitempty"`
	// The Node data for the node who owns this KeyPiece
	OwnerNode *Node `protobuf:"bytes,5,opt,name=owner_node,json=ownerNode" json:"owner_node,omitempty"`
}

func (m *KeyPiece) Reset()                    { *m = KeyPiece{} }
func (m *KeyPiece) String() string            { return proto.CompactTextString(m) }
func (*KeyPiece) ProtoMessage()               {}
func (*KeyPiece) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *KeyPiece) GetOwnerNode() *Node {
	if m != nil {
		return m.OwnerNode
	}
	return nil
}

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "paranoid.EmptyMessage")
	proto.RegisterType((*Node)(nil), "paranoid.Node")
	proto.RegisterType((*JoinClusterRequest)(nil), "paranoid.JoinClusterRequest")
	proto.RegisterType((*NewGenerationRequest)(nil), "paranoid.NewGenerationRequest")
	proto.RegisterType((*NewGenerationResponse)(nil), "paranoid.NewGenerationResponse")
	proto.RegisterType((*KeyPiece)(nil), "paranoid.KeyPiece")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for ParanoidNetwork service

type ParanoidNetworkClient interface {
	// Used for health checking and discovery. Sends the IP and port of the
	// PFSD instance running on the client.
	Ping(ctx context.Context, in *Node, opts ...grpc.CallOption) (*EmptyMessage, error)
	// Used by a new node to let other nodes it is available to join the cluster.
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	// Used by a new node to create a new key generation before joining the cluster.
	NewGeneration(ctx context.Context, in *NewGenerationRequest, opts ...grpc.CallOption) (*NewGenerationResponse, error)
	// Cryptography calls
	SendKeyPiece(ctx context.Context, in *KeyPiece, opts ...grpc.CallOption) (*EmptyMessage, error)
	RequestKeyPiece(ctx context.Context, in *Node, opts ...grpc.CallOption) (*KeyPiece, error)
}

type paranoidNetworkClient struct {
	cc *grpc.ClientConn
}

func NewParanoidNetworkClient(cc *grpc.ClientConn) ParanoidNetworkClient {
	return &paranoidNetworkClient{cc}
}

func (c *paranoidNetworkClient) Ping(ctx context.Context, in *Node, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/JoinCluster", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) NewGeneration(ctx context.Context, in *NewGenerationRequest, opts ...grpc.CallOption) (*NewGenerationResponse, error) {
	out := new(NewGenerationResponse)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/NewGeneration", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) SendKeyPiece(ctx context.Context, in *KeyPiece, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/SendKeyPiece", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paranoidNetworkClient) RequestKeyPiece(ctx context.Context, in *Node, opts ...grpc.CallOption) (*KeyPiece, error) {
	out := new(KeyPiece)
	err := grpc.Invoke(ctx, "/paranoid.ParanoidNetwork/RequestKeyPiece", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ParanoidNetwork service

type ParanoidNetworkServer interface {
	// Used for health checking and discovery. Sends the IP and port of the
	// PFSD instance running on the client.
	Ping(context.Context, *Node) (*EmptyMessage, error)
	// Used by a new node to let other nodes it is available to join the cluster.
	JoinCluster(context.Context, *JoinClusterRequest) (*EmptyMessage, error)
	// Used by a new node to create a new key generation before joining the cluster.
	NewGeneration(context.Context, *NewGenerationRequest) (*NewGenerationResponse, error)
	// Cryptography calls
	SendKeyPiece(context.Context, *KeyPiece) (*EmptyMessage, error)
	RequestKeyPiece(context.Context, *Node) (*KeyPiece, error)
}

func RegisterParanoidNetworkServer(s *grpc.Server, srv ParanoidNetworkServer) {
	s.RegisterService(&_ParanoidNetwork_serviceDesc, srv)
}

func _ParanoidNetwork_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParanoidNetworkServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paranoid.ParanoidNetwork/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParanoidNetworkServer).Ping(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParanoidNetwork_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParanoidNetworkServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paranoid.ParanoidNetwork/JoinCluster",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParanoidNetworkServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParanoidNetwork_NewGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGenerationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParanoidNetworkServer).NewGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paranoid.ParanoidNetwork/NewGeneration",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParanoidNetworkServer).NewGeneration(ctx, req.(*NewGenerationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParanoidNetwork_SendKeyPiece_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeyPiece)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParanoidNetworkServer).SendKeyPiece(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paranoid.ParanoidNetwork/SendKeyPiece",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParanoidNetworkServer).SendKeyPiece(ctx, req.(*KeyPiece))
	}
	return interceptor(ctx, in, info, handler)
}

func _ParanoidNetwork_RequestKeyPiece_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Node)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParanoidNetworkServer).RequestKeyPiece(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/paranoid.ParanoidNetwork/RequestKeyPiece",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParanoidNetworkServer).RequestKeyPiece(ctx, req.(*Node))
	}
	return interceptor(ctx, in, info, handler)
}

var _ParanoidNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "paranoid.ParanoidNetwork",
	HandlerType: (*ParanoidNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ParanoidNetwork_Ping_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _ParanoidNetwork_JoinCluster_Handler,
		},
		{
			MethodName: "NewGeneration",
			Handler:    _ParanoidNetwork_NewGeneration_Handler,
		},
		{
			MethodName: "SendKeyPiece",
			Handler:    _ParanoidNetwork_SendKeyPiece_Handler,
		},
		{
			MethodName: "RequestKeyPiece",
			Handler:    _ParanoidNetwork_RequestKeyPiece_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 459 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x6d, 0xe2, 0x04, 0xb5, 0x13, 0x37, 0x6d, 0x47, 0x05, 0x59, 0x15, 0x6a, 0x91, 0xe1, 0x80,
	0x84, 0x28, 0xa8, 0x1c, 0xb8, 0x70, 0x43, 0x05, 0x09, 0x84, 0x89, 0x96, 0x0f, 0xb0, 0xb6, 0xf5,
	0x10, 0x2d, 0xd4, 0xbb, 0xdb, 0xdd, 0xb5, 0xa2, 0xfe, 0x06, 0xdf, 0xc0, 0x2f, 0xf1, 0x3f, 0xac,
	0x77, 0x93, 0xb8, 0x0d, 0x21, 0xb7, 0xde, 0xde, 0xbc, 0xe7, 0x79, 0x33, 0x7a, 0x3b, 0x86, 0x63,
	0xcd, 0x0d, 0x97, 0x4a, 0x54, 0x92, 0xdc, 0x4c, 0x99, 0x9f, 0xaf, 0x16, 0xf5, 0xa9, 0x36, 0xca,
	0x29, 0xdc, 0x5e, 0xd4, 0xf9, 0x18, 0xd2, 0xf3, 0x5a, 0xbb, 0x9b, 0x2f, 0x64, 0x2d, 0x9f, 0x52,
	0x5e, 0xc2, 0xa0, 0x50, 0x15, 0xe1, 0x18, 0xfa, 0x42, 0x67, 0xbd, 0x27, 0xbd, 0xe7, 0x3b, 0xcc,
	0x23, 0x44, 0x18, 0x68, 0x65, 0x5c, 0xd6, 0x0f, 0x4c, 0xc0, 0x78, 0x02, 0xa3, 0x4b, 0x55, 0xd7,
	0x4a, 0x96, 0x92, 0xd7, 0x94, 0x25, 0x41, 0x82, 0x48, 0x15, 0x9e, 0x69, 0x9b, 0x9a, 0x46, 0x54,
	0xd9, 0x20, 0x36, 0xb5, 0x38, 0xff, 0xd5, 0x03, 0xfc, 0xa4, 0x84, 0x7c, 0x7f, 0xd5, 0x58, 0x47,
	0x86, 0xd1, 0x75, 0x43, 0xd6, 0xdd, 0xdb, 0x3c, 0x7c, 0x0a, 0xbb, 0x5a, 0xa9, 0xab, 0x52, 0x73,
	0x6b, 0x7d, 0x14, 0x55, 0x36, 0x0c, 0x62, 0xda, 0x92, 0x93, 0x39, 0x97, 0x7f, 0x85, 0xc3, 0x82,
	0x66, 0x1f, 0x49, 0x92, 0xe1, 0x4e, 0x28, 0xb9, 0xd8, 0xea, 0x2d, 0xec, 0x99, 0x08, 0x85, 0x9c,
	0x96, 0xd2, 0x07, 0x13, 0x56, 0x1c, 0x9d, 0x8d, 0x4f, 0x97, 0x89, 0xb6, 0x71, 0xb1, 0x71, 0xf7,
	0x59, 0x5b, 0xe7, 0x3f, 0xe0, 0xe1, 0x8a, 0xa1, 0xd5, 0x4a, 0x5a, 0xc2, 0x17, 0x70, 0x30, 0x5d,
	0xb2, 0xa5, 0x6c, 0xea, 0x0b, 0x32, 0xc1, 0x33, 0x61, 0xfb, 0x9d, 0x50, 0x04, 0x1e, 0x9f, 0xc1,
	0x50, 0x13, 0x19, 0xeb, 0x53, 0x48, 0xd6, 0x0c, 0x8d, 0x62, 0xfe, 0xbb, 0x07, 0xdb, 0x9f, 0xe9,
	0x66, 0x22, 0xe8, 0x32, 0x44, 0x50, 0x71, 0xc7, 0x83, 0x65, 0xca, 0x02, 0xc6, 0x97, 0x80, 0xbe,
	0x91, 0xa4, 0x2b, 0xbf, 0xfb, 0xfd, 0xc8, 0x68, 0x23, 0x64, 0x4c, 0x36, 0x65, 0x07, 0x51, 0xf9,
	0xd0, 0x09, 0x78, 0xe8, 0xa7, 0x1a, 0x31, 0x0f, 0x38, 0x65, 0xb1, 0xc0, 0x7d, 0x48, 0x2c, 0x5d,
	0x87, 0x68, 0x13, 0xd6, 0x42, 0x6f, 0x0b, 0x6a, 0xe6, 0x37, 0x8e, 0xb9, 0x0c, 0xd7, 0xe6, 0xb2,
	0x13, 0xbe, 0x68, 0xe1, 0xd9, 0x9f, 0x3e, 0xec, 0x4d, 0xe6, 0x62, 0x11, 0xcf, 0x12, 0x5f, 0xc3,
	0x60, 0xe2, 0x27, 0xe3, 0x4a, 0xdb, 0xd1, 0xa3, 0xae, 0xbe, 0x73, 0x9d, 0x5b, 0x78, 0x0e, 0xa3,
	0x5b, 0xd7, 0x83, 0x8f, 0xbb, 0x0f, 0xff, 0x3d, 0xaa, 0x0d, 0x36, 0x0c, 0x76, 0xef, 0xbc, 0x0f,
	0x1e, 0xdf, 0xda, 0x60, 0xcd, 0x25, 0x1c, 0x9d, 0xfc, 0x57, 0x8f, 0x0f, 0xeb, 0x3d, 0xdf, 0x41,
	0xfa, 0x8d, 0x64, 0xd5, 0x3d, 0x45, 0xd7, 0xb2, 0xe0, 0x36, 0x6c, 0xe4, 0x4f, 0x6d, 0x3e, 0x6b,
	0x69, 0xb0, 0x9a, 0xca, 0x1a, 0xc3, 0x7c, 0xeb, 0xe2, 0x41, 0xf8, 0xa5, 0xdf, 0xfc, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x39, 0xd2, 0xea, 0x3f, 0xf4, 0x03, 0x00, 0x00,
}
