// Code generated by protoc-gen-go.
// source: discoverynetwork/discovery.proto
// DO NOT EDIT!

/*
Package discoverynetwork is a generated protocol buffer package.

It is generated from these files:
	discoverynetwork/discovery.proto

It has these top-level messages:
	EmptyMessage
	DisconnectRequest
	JoinRequest
	JoinResponse
	Node
*/
package discoverynetwork

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DisconnectRequest struct {
	Pool     string `protobuf:"bytes,1,opt,name=pool" json:"pool,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Node     *Node  `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
}

func (m *DisconnectRequest) Reset()                    { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string            { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()               {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DisconnectRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type JoinRequest struct {
	Pool     string `protobuf:"bytes,1,opt,name=pool" json:"pool,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Node     *Node  `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JoinRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type JoinResponse struct {
	// The time after which the server will remove the node from the list
	// if the node doesn't make the Renew RPC call
	ResetInterval int64   `protobuf:"varint,1,opt,name=reset_interval,json=resetInterval" json:"reset_interval,omitempty"`
	Nodes         []*Node `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *JoinResponse) Reset()                    { *m = JoinResponse{} }
func (m *JoinResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()               {}
func (*JoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JoinResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Ip         string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port       string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	CommonName string `protobuf:"bytes,3,opt,name=common_name,json=commonName" json:"common_name,omitempty"`
	Uuid       string `protobuf:"bytes,4,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "discoverynetwork.EmptyMessage")
	proto.RegisterType((*DisconnectRequest)(nil), "discoverynetwork.DisconnectRequest")
	proto.RegisterType((*JoinRequest)(nil), "discoverynetwork.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "discoverynetwork.JoinResponse")
	proto.RegisterType((*Node)(nil), "discoverynetwork.Node")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for DiscoveryNetwork service

type DiscoveryNetworkClient interface {
	// Discovery Calls
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type discoveryNetworkClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryNetworkClient(cc *grpc.ClientConn) DiscoveryNetworkClient {
	return &discoveryNetworkClient{cc}
}

func (c *discoveryNetworkClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := grpc.Invoke(ctx, "/discoverynetwork.DiscoveryNetwork/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryNetworkClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/discoverynetwork.DiscoveryNetwork/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiscoveryNetwork service

type DiscoveryNetworkServer interface {
	// Discovery Calls
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*EmptyMessage, error)
}

func RegisterDiscoveryNetworkServer(s *grpc.Server, srv DiscoveryNetworkServer) {
	s.RegisterService(&_DiscoveryNetwork_serviceDesc, srv)
}

func _DiscoveryNetwork_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryNetworkServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discoverynetwork.DiscoveryNetwork/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryNetworkServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscoveryNetwork_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryNetworkServer).Disconnect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discoverynetwork.DiscoveryNetwork/Disconnect",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryNetworkServer).Disconnect(ctx, req.(*DisconnectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscoveryNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discoverynetwork.DiscoveryNetwork",
	HandlerType: (*DiscoveryNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _DiscoveryNetwork_Join_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _DiscoveryNetwork_Disconnect_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x52, 0xdb, 0x4a, 0x03, 0x31,
	0x10, 0xed, 0x65, 0x15, 0x3b, 0xad, 0xa5, 0xce, 0x83, 0x2c, 0x05, 0xb5, 0xac, 0x08, 0x22, 0x52,
	0xa1, 0xfe, 0x42, 0x45, 0x14, 0xec, 0xc3, 0xfa, 0x01, 0x65, 0xdd, 0x1d, 0x64, 0xd1, 0xcd, 0xc4,
	0x24, 0xad, 0xf4, 0xaf, 0xfc, 0x44, 0x73, 0xa9, 0x55, 0x5b, 0xf5, 0xd1, 0xb7, 0x93, 0x93, 0x33,
	0x39, 0x73, 0x26, 0x03, 0x83, 0xa2, 0xd4, 0x39, 0xcf, 0x49, 0x2d, 0x04, 0x99, 0x57, 0x56, 0x4f,
	0x17, 0x2b, 0x62, 0x28, 0x15, 0x1b, 0xc6, 0xde, 0xba, 0x22, 0xe9, 0x42, 0xe7, 0xaa, 0x92, 0x66,
	0x71, 0x47, 0x5a, 0x67, 0x8f, 0x94, 0x30, 0xec, 0x8d, 0x9d, 0x46, 0x08, 0xca, 0x4d, 0x4a, 0x2f,
	0x33, 0xd2, 0x06, 0x11, 0x22, 0xc9, 0xfc, 0x1c, 0xd7, 0x07, 0xf5, 0xd3, 0x56, 0xea, 0x31, 0xf6,
	0x61, 0x47, 0x66, 0x5a, 0xdb, 0x47, 0x8a, 0xb8, 0xe1, 0xf9, 0xd5, 0x19, 0xcf, 0x20, 0x12, 0x5c,
	0x50, 0xdc, 0xb4, 0x7c, 0x7b, 0xb4, 0x3f, 0x5c, 0x77, 0x1d, 0x4e, 0xec, 0x6d, 0xea, 0x35, 0x49,
	0x09, 0xed, 0x5b, 0x2e, 0xc5, 0x7f, 0x58, 0xe5, 0xd0, 0x09, 0x56, 0x5a, 0xb2, 0xd0, 0x84, 0x27,
	0xd0, 0x55, 0xa4, 0xc9, 0x4c, 0x4b, 0x61, 0x48, 0xcd, 0xb3, 0xe0, 0xda, 0x4c, 0x77, 0x3d, 0x7b,
	0xb3, 0x24, 0xf1, 0x1c, 0xb6, 0x5c, 0xb9, 0xb6, 0xde, 0xcd, 0x3f, 0x3c, 0x82, 0x28, 0x99, 0x42,
	0xe4, 0x8e, 0xd8, 0x85, 0x46, 0x29, 0x97, 0x31, 0x2c, 0x0a, 0xc1, 0x94, 0x59, 0x06, 0xf0, 0x18,
	0x8f, 0xa0, 0x9d, 0x73, 0x55, 0xb1, 0x98, 0x8a, 0xac, 0x0a, 0x19, 0x5a, 0x29, 0x04, 0x6a, 0x62,
	0x19, 0x57, 0x34, 0x9b, 0x95, 0x45, 0x1c, 0x85, 0x22, 0x87, 0x47, 0x6f, 0x75, 0xe8, 0x8d, 0x3f,
	0x3a, 0x98, 0x84, 0x0e, 0xf0, 0x1a, 0x22, 0x17, 0x0d, 0x0f, 0x36, 0x9b, 0xfb, 0x32, 0xdd, 0xfe,
	0xe1, 0x6f, 0xd7, 0x61, 0x22, 0x49, 0x0d, 0xef, 0x01, 0x3e, 0xff, 0x1f, 0x8f, 0x37, 0xf5, 0x1b,
	0xdb, 0xf1, 0xd3, 0xa3, 0xdf, 0x56, 0xaa, 0xf6, 0xb0, 0xed, 0xb7, 0xef, 0xf2, 0x3d, 0x00, 0x00,
	0xff, 0xff, 0x68, 0xf6, 0x4b, 0x3a, 0xa1, 0x02, 0x00, 0x00,
}
