// Code generated by protoc-gen-go.
// source: discoverynetwork/discovery.proto
// DO NOT EDIT!

/*
Package discoverynetwork is a generated protocol buffer package.

It is generated from these files:
	discoverynetwork/discovery.proto

It has these top-level messages:
	EmptyMessage
	DisconnectRequest
	JoinRequest
	JoinResponse
	Node
*/
package discoverynetwork

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DisconnectRequest struct {
	Node *Node `protobuf:"bytes,1,opt,name=node" json:"node,omitempty"`
}

func (m *DisconnectRequest) Reset()                    { *m = DisconnectRequest{} }
func (m *DisconnectRequest) String() string            { return proto.CompactTextString(m) }
func (*DisconnectRequest) ProtoMessage()               {}
func (*DisconnectRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DisconnectRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type JoinRequest struct {
	Pool string `protobuf:"bytes,1,opt,name=pool" json:"pool,omitempty"`
	Node *Node  `protobuf:"bytes,2,opt,name=node" json:"node,omitempty"`
}

func (m *JoinRequest) Reset()                    { *m = JoinRequest{} }
func (m *JoinRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()               {}
func (*JoinRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *JoinRequest) GetNode() *Node {
	if m != nil {
		return m.Node
	}
	return nil
}

type JoinResponse struct {
	// The time after which the server will remove the node from the list
	// if the node doesn't make the Renew RPC call
	ResetInterval int64   `protobuf:"varint,1,opt,name=reset_interval" json:"reset_interval,omitempty"`
	Nodes         []*Node `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *JoinResponse) Reset()                    { *m = JoinResponse{} }
func (m *JoinResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()               {}
func (*JoinResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *JoinResponse) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Node struct {
	Ip         string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port       string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	CommonName string `protobuf:"bytes,3,opt,name=common_name" json:"common_name,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "discoverynetwork.EmptyMessage")
	proto.RegisterType((*DisconnectRequest)(nil), "discoverynetwork.DisconnectRequest")
	proto.RegisterType((*JoinRequest)(nil), "discoverynetwork.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "discoverynetwork.JoinResponse")
	proto.RegisterType((*Node)(nil), "discoverynetwork.Node")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for DiscoveryNetwork service

type DiscoveryNetworkClient interface {
	// Discovery Calls
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	Renew(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type discoveryNetworkClient struct {
	cc *grpc.ClientConn
}

func NewDiscoveryNetworkClient(cc *grpc.ClientConn) DiscoveryNetworkClient {
	return &discoveryNetworkClient{cc}
}

func (c *discoveryNetworkClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := grpc.Invoke(ctx, "/discoverynetwork.DiscoveryNetwork/Join", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryNetworkClient) Disconnect(ctx context.Context, in *DisconnectRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/discoverynetwork.DiscoveryNetwork/Disconnect", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryNetworkClient) Renew(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/discoverynetwork.DiscoveryNetwork/Renew", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DiscoveryNetwork service

type DiscoveryNetworkServer interface {
	// Discovery Calls
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Disconnect(context.Context, *DisconnectRequest) (*EmptyMessage, error)
	Renew(context.Context, *JoinRequest) (*EmptyMessage, error)
}

func RegisterDiscoveryNetworkServer(s *grpc.Server, srv DiscoveryNetworkServer) {
	s.RegisterService(&_DiscoveryNetwork_serviceDesc, srv)
}

func _DiscoveryNetwork_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DiscoveryNetworkServer).Join(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _DiscoveryNetwork_Disconnect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DisconnectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DiscoveryNetworkServer).Disconnect(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _DiscoveryNetwork_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(DiscoveryNetworkServer).Renew(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _DiscoveryNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discoverynetwork.DiscoveryNetwork",
	HandlerType: (*DiscoveryNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _DiscoveryNetwork_Join_Handler,
		},
		{
			MethodName: "Disconnect",
			Handler:    _DiscoveryNetwork_Disconnect_Handler,
		},
		{
			MethodName: "Renew",
			Handler:    _DiscoveryNetwork_Renew_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x80, 0x9b, 0x26, 0x15, 0x3a, 0x09, 0xa5, 0x8e, 0x50, 0x8a, 0xa0, 0x94, 0xa8, 0xe0, 0x29,
	0x42, 0xc5, 0x83, 0x47, 0xa1, 0xa2, 0x08, 0xed, 0xa1, 0x3e, 0x40, 0x89, 0xe9, 0x20, 0x41, 0x33,
	0x13, 0x77, 0xd7, 0x96, 0xbe, 0xba, 0x27, 0xbb, 0x89, 0xad, 0xb6, 0xd1, 0x1e, 0x3c, 0x2d, 0xcc,
	0xcf, 0xb7, 0xdf, 0xcc, 0x2e, 0xf4, 0xa6, 0xa9, 0x4e, 0x64, 0x46, 0x6a, 0xc1, 0x64, 0xe6, 0xa2,
	0x5e, 0x2e, 0xd6, 0x81, 0x28, 0x57, 0x62, 0x04, 0xdb, 0xdb, 0x15, 0x61, 0x0b, 0x82, 0xdb, 0x2c,
	0x37, 0x8b, 0x21, 0x69, 0x1d, 0x3f, 0x53, 0x78, 0x0d, 0xfb, 0x03, 0x5b, 0xc3, 0x4c, 0x89, 0x19,
	0xd3, 0xdb, 0x3b, 0x69, 0x83, 0xa7, 0xe0, 0xb1, 0x4c, 0xa9, 0xeb, 0xf4, 0x9c, 0x73, 0xbf, 0xdf,
	0x89, 0xb6, 0x29, 0xd1, 0x68, 0x99, 0x0d, 0x6f, 0xc0, 0x7f, 0x90, 0x94, 0x57, 0x4d, 0x01, 0x78,
	0xb9, 0xc8, 0x6b, 0xd1, 0xd4, 0x5c, 0x23, 0xea, 0x3b, 0x11, 0x43, 0x08, 0x4a, 0x84, 0xce, 0x85,
	0x35, 0x61, 0x07, 0x5a, 0x8a, 0x34, 0x99, 0x49, 0xca, 0x86, 0xd4, 0x2c, 0x2e, 0x69, 0x2e, 0x9e,
	0x41, 0xc3, 0xd2, 0xf4, 0x12, 0xe7, 0xee, 0xc0, 0x5d, 0x81, 0x67, 0x4f, 0x04, 0xa8, 0xa7, 0xf9,
	0x97, 0x48, 0xa1, 0xa5, 0x4c, 0x21, 0xd2, 0xc4, 0x03, 0xf0, 0x13, 0xc9, 0x32, 0xe1, 0x09, 0xc7,
	0x19, 0x75, 0x5d, 0x1b, 0xec, 0x7f, 0x38, 0xd0, 0x1e, 0xac, 0x80, 0xa3, 0x12, 0x88, 0x77, 0xe0,
	0x59, 0x35, 0x3c, 0xaa, 0xde, 0xf5, 0x63, 0xea, 0xc3, 0xe3, 0xbf, 0xd2, 0xe5, 0x44, 0x61, 0x0d,
	0x1f, 0x01, 0xbe, 0x37, 0x8c, 0x27, 0xd5, 0xfa, 0xca, 0xfe, 0x7f, 0x83, 0x6e, 0x3c, 0x5a, 0x0d,
	0xef, 0xa1, 0x31, 0x26, 0xa6, 0xf9, 0x3f, 0xf4, 0x36, 0x49, 0x4f, 0x7b, 0xc5, 0x4f, 0xb9, 0xfc,
	0x0c, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xd9, 0x8b, 0xc6, 0x4d, 0x02, 0x00, 0x00,
}
