// Code generated by protoc-gen-go.
// source: raft/raft.proto
// DO NOT EDIT!

/*
Package raft is a generated protocol buffer package.

It is generated from these files:
	raft/raft.proto

It has these top-level messages:
	EmptyMessage
	EntryRequest
	AppendEntriesRequest
	StateMachineCommand
	Node
	Configuration
	Entry
	AppendEntriesResponse
	RequestVoteRequest
	RequestVoteResponse
*/
package raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Entry_EntryType int32

const (
	Entry_StateMachineCommand Entry_EntryType = 0
	Entry_ConfigurationChange Entry_EntryType = 1
)

var Entry_EntryType_name = map[int32]string{
	0: "StateMachineCommand",
	1: "ConfigurationChange",
}
var Entry_EntryType_value = map[string]int32{
	"StateMachineCommand": 0,
	"ConfigurationChange": 1,
}

func (x Entry_EntryType) String() string {
	return proto.EnumName(Entry_EntryType_name, int32(x))
}
func (Entry_EntryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EntryRequest struct {
	Entry *Entry `protobuf:"bytes,1,opt,name=entry" json:"entry,omitempty"`
}

func (m *EntryRequest) Reset()                    { *m = EntryRequest{} }
func (m *EntryRequest) String() string            { return proto.CompactTextString(m) }
func (*EntryRequest) ProtoMessage()               {}
func (*EntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EntryRequest) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type AppendEntriesRequest struct {
	Term         uint64   `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderId     string   `protobuf:"bytes,2,opt,name=leader_id" json:"leader_id,omitempty"`
	PrevLogIndex uint64   `protobuf:"varint,3,opt,name=prev_log_index" json:"prev_log_index,omitempty"`
	PrevLogTerm  uint64   `protobuf:"varint,4,opt,name=prev_log_term" json:"prev_log_term,omitempty"`
	Entries      []*Entry `protobuf:"bytes,5,rep,name=entries" json:"entries,omitempty"`
	LeaderCommit uint64   `protobuf:"varint,6,opt,name=leader_commit" json:"leader_commit,omitempty"`
}

func (m *AppendEntriesRequest) Reset()                    { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()               {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppendEntriesRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

// Will be replaced with pfs commands
type StateMachineCommand struct {
	Number uint64 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *StateMachineCommand) Reset()                    { *m = StateMachineCommand{} }
func (m *StateMachineCommand) String() string            { return proto.CompactTextString(m) }
func (*StateMachineCommand) ProtoMessage()               {}
func (*StateMachineCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Node struct {
	Ip         string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port       string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	CommonName string `protobuf:"bytes,3,opt,name=common_name" json:"common_name,omitempty"`
	NodeId     string `protobuf:"bytes,4,opt,name=node_id" json:"node_id,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Configuration struct {
	Nodes []*Node `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Configuration) Reset()                    { *m = Configuration{} }
func (m *Configuration) String() string            { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()               {}
func (*Configuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Configuration) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type Entry struct {
	Type    Entry_EntryType      `protobuf:"varint,1,opt,name=type,enum=raft.Entry_EntryType" json:"type,omitempty"`
	Command *StateMachineCommand `protobuf:"bytes,2,opt,name=command" json:"command,omitempty"`
	Config  *Configuration       `protobuf:"bytes,3,opt,name=config" json:"config,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Entry) GetCommand() *StateMachineCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Entry) GetConfig() *Configuration {
	if m != nil {
		return m.Config
	}
	return nil
}

type AppendEntriesResponse struct {
	Term    uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Success bool   `protobuf:"varint,2,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type RequestVoteRequest struct {
	Term         uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	CandidateId  string `protobuf:"bytes,2,opt,name=candidate_id" json:"candidate_id,omitempty"`
	LastLogIndex uint64 `protobuf:"varint,3,opt,name=last_log_index" json:"last_log_index,omitempty"`
	LastLogTerm  uint64 `protobuf:"varint,4,opt,name=last_log_term" json:"last_log_term,omitempty"`
}

func (m *RequestVoteRequest) Reset()                    { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()               {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type RequestVoteResponse struct {
	Term        uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool   `protobuf:"varint,2,opt,name=vote_granted" json:"vote_granted,omitempty"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "raft.EmptyMessage")
	proto.RegisterType((*EntryRequest)(nil), "raft.EntryRequest")
	proto.RegisterType((*AppendEntriesRequest)(nil), "raft.AppendEntriesRequest")
	proto.RegisterType((*StateMachineCommand)(nil), "raft.StateMachineCommand")
	proto.RegisterType((*Node)(nil), "raft.Node")
	proto.RegisterType((*Configuration)(nil), "raft.Configuration")
	proto.RegisterType((*Entry)(nil), "raft.Entry")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raft.AppendEntriesResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "raft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "raft.RequestVoteResponse")
	proto.RegisterEnum("raft.Entry_EntryType", Entry_EntryType_name, Entry_EntryType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for RaftNetwork service

type RaftNetworkClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	ClientToLeaderRequest(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type raftNetworkClient struct {
	cc *grpc.ClientConn
}

func NewRaftNetworkClient(cc *grpc.ClientConn) RaftNetworkClient {
	return &raftNetworkClient{cc}
}

func (c *raftNetworkClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/raft.RaftNetwork/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNetworkClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := grpc.Invoke(ctx, "/raft.RaftNetwork/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNetworkClient) ClientToLeaderRequest(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/raft.RaftNetwork/ClientToLeaderRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RaftNetwork service

type RaftNetworkServer interface {
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	ClientToLeaderRequest(context.Context, *EntryRequest) (*EmptyMessage, error)
}

func RegisterRaftNetworkServer(s *grpc.Server, srv RaftNetworkServer) {
	s.RegisterService(&_RaftNetwork_serviceDesc, srv)
}

func _RaftNetwork_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RaftNetworkServer).AppendEntries(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RaftNetwork_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RaftNetworkServer).RequestVote(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _RaftNetwork_ClientToLeaderRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(EntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(RaftNetworkServer).ClientToLeaderRequest(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _RaftNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raft.RaftNetwork",
	HandlerType: (*RaftNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _RaftNetwork_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _RaftNetwork_RequestVote_Handler,
		},
		{
			MethodName: "ClientToLeaderRequest",
			Handler:    _RaftNetwork_ClientToLeaderRequest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x94, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0x86, 0xeb, 0x36, 0x97, 0xfa, 0x38, 0x49, 0xcb, 0xa4, 0x01, 0x27, 0xb0, 0xa8, 0xa6, 0x42,
	0x42, 0x5d, 0x14, 0x29, 0x48, 0x48, 0x2c, 0x58, 0x54, 0x01, 0x16, 0x88, 0x76, 0x51, 0x2a, 0xb6,
	0xd1, 0xd4, 0x3e, 0x75, 0x47, 0xc4, 0x33, 0x66, 0x3c, 0x29, 0xe4, 0x59, 0x78, 0x15, 0x9e, 0x86,
	0x27, 0x61, 0x2e, 0xb9, 0x39, 0x78, 0x63, 0x65, 0xce, 0xe5, 0x3f, 0xdf, 0x1c, 0xff, 0x0e, 0x1c,
	0x29, 0x76, 0xaf, 0x5f, 0xdb, 0xc7, 0x45, 0xa1, 0xa4, 0x96, 0xa4, 0x61, 0x7f, 0xd3, 0x1e, 0x74,
	0x3e, 0xe6, 0x85, 0x5e, 0x5c, 0x61, 0x59, 0xb2, 0x0c, 0xe9, 0xb9, 0x39, 0x0b, 0xad, 0x16, 0x37,
	0xf8, 0x63, 0x8e, 0xa5, 0x26, 0x23, 0x68, 0xa2, 0x3d, 0xc7, 0xc1, 0x69, 0xf0, 0x2a, 0x1a, 0x47,
	0x17, 0x4e, 0xc1, 0x95, 0xd0, 0xdf, 0x01, 0x9c, 0x5c, 0x16, 0x05, 0x8a, 0xd4, 0x9e, 0x39, 0x96,
	0xab, 0xa6, 0x0e, 0x34, 0x34, 0xaa, 0xdc, 0xf5, 0x34, 0xc8, 0x13, 0x08, 0x67, 0xc8, 0x52, 0x54,
	0x53, 0x9e, 0xc6, 0xfb, 0x26, 0x14, 0x92, 0xa7, 0xd0, 0x2b, 0x14, 0x3e, 0x4e, 0x67, 0x32, 0x9b,
	0x72, 0x91, 0xe2, 0xaf, 0xf8, 0xc0, 0x95, 0x0e, 0xa0, 0xbb, 0x8e, 0x3b, 0x85, 0x86, 0x0b, 0xbf,
	0x80, 0x36, 0xfa, 0x09, 0x71, 0xf3, 0xf4, 0x60, 0x07, 0xc3, 0x36, 0x2d, 0xf5, 0x13, 0x99, 0xe7,
	0x5c, 0xc7, 0x2d, 0xdb, 0x44, 0x5f, 0x42, 0xff, 0xab, 0x66, 0x1a, 0xaf, 0x58, 0xf2, 0xc0, 0x05,
	0x4e, 0x4c, 0x8e, 0x89, 0x94, 0xf4, 0xa0, 0x25, 0xe6, 0xf9, 0x1d, 0x2a, 0x4f, 0x47, 0x3f, 0x41,
	0xe3, 0x5a, 0xa6, 0x48, 0x00, 0xf6, 0x79, 0xe1, 0x62, 0xa1, 0xe5, 0x2f, 0xa4, 0xd2, 0x4b, 0xd8,
	0x3e, 0x44, 0x56, 0x58, 0x8a, 0xa9, 0x60, 0x39, 0x3a, 0xd2, 0x90, 0x1c, 0x41, 0x5b, 0x98, 0x36,
	0x7b, 0x25, 0xcb, 0x18, 0x9a, 0xc5, 0x75, 0x27, 0x52, 0xdc, 0xf3, 0x6c, 0xae, 0x98, 0xe6, 0x52,
	0x90, 0x21, 0x34, 0x6d, 0x45, 0x69, 0x34, 0x2d, 0x32, 0x78, 0x64, 0x3b, 0x8b, 0xfe, 0x09, 0xa0,
	0xe9, 0xd9, 0xcf, 0xcc, 0xa6, 0x16, 0x05, 0xba, 0xb9, 0xbd, 0xf1, 0x60, 0xeb, 0x5a, 0xfe, 0x79,
	0x6b, 0x92, 0xe4, 0x1c, 0xda, 0x89, 0xa7, 0x77, 0x44, 0xd1, 0x78, 0xe8, 0xeb, 0xea, 0xae, 0x77,
	0x06, 0xad, 0xc4, 0x61, 0x38, 0xce, 0x68, 0xdc, 0xf7, 0xa5, 0x15, 0x34, 0xfa, 0x1e, 0xc2, 0x8d,
	0xfa, 0xb3, 0xda, 0x3d, 0x1d, 0xef, 0xd9, 0x44, 0xa5, 0x6d, 0xf2, 0xc0, 0x44, 0x86, 0xc7, 0x01,
	0x7d, 0x0b, 0x83, 0x9d, 0xd7, 0x5e, 0x16, 0x52, 0x94, 0xb8, 0xf3, 0xde, 0xcd, 0x8a, 0xca, 0x79,
	0x92, 0x18, 0x63, 0x39, 0xec, 0x43, 0x9a, 0x01, 0x59, 0x3a, 0xe4, 0x9b, 0xd4, 0x58, 0x6f, 0x96,
	0x13, 0xe8, 0x24, 0x66, 0x3c, 0x4f, 0x0d, 0x51, 0xc5, 0x2f, 0x33, 0x56, 0xea, 0x3a, 0xbf, 0xac,
	0xe3, 0x1b, 0xbf, 0xd0, 0x77, 0xd0, 0xaf, 0x0c, 0xaa, 0xc5, 0x33, 0x93, 0x1e, 0x4d, 0x76, 0x9a,
	0x29, 0x26, 0x34, 0xfa, 0x49, 0x87, 0xe3, 0xbf, 0x01, 0x44, 0x37, 0x66, 0x63, 0xd7, 0xa8, 0x7f,
	0x4a, 0xf5, 0x9d, 0x7c, 0x86, 0x6e, 0xe5, 0xae, 0x64, 0xe4, 0x17, 0x5a, 0xe7, 0xfb, 0xd1, 0xf3,
	0xda, 0x9c, 0x9f, 0x4e, 0xf7, 0xc8, 0x07, 0x23, 0xbd, 0xc1, 0x22, 0xb1, 0xaf, 0xfe, 0x7f, 0x25,
	0xa3, 0x61, 0x4d, 0x66, 0xad, 0x72, 0x09, 0x83, 0xc9, 0x8c, 0x9b, 0xef, 0xe1, 0x56, 0x7e, 0x71,
	0xb6, 0x5f, 0x2d, 0x92, 0x6c, 0xb9, 0x67, 0xa5, 0xb4, 0x8a, 0x6d, 0x7f, 0xe2, 0x7b, 0x77, 0x2d,
	0xf7, 0x0f, 0xf0, 0xe6, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0xdb, 0x17, 0xb6, 0x14, 0x04,
	0x00, 0x00,
}
