// Code generated by protoc-gen-go.
// source: raft/raft.proto
// DO NOT EDIT!

/*
Package raft is a generated protocol buffer package.

It is generated from these files:
	raft/raft.proto

It has these top-level messages:
	EmptyMessage
	EntryRequest
	AppendEntriesRequest
	StateMachineCommand
	KeyStateCommand
	Node
	Configuration
	DemoCommand
	Entry
	LogEntry
	AppendEntriesResponse
	RequestVoteRequest
	RequestVoteResponse
	SnapshotRequest
	SnapshotResponse
	LeaderDataRequest
	LeaderData
*/
package raft

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type KeyStateCommand_KSMType int32

const (
	KeyStateCommand_UpdateKeyPiece KeyStateCommand_KSMType = 0
	KeyStateCommand_NewGeneration  KeyStateCommand_KSMType = 1
	KeyStateCommand_OwnerComplete  KeyStateCommand_KSMType = 2
)

var KeyStateCommand_KSMType_name = map[int32]string{
	0: "UpdateKeyPiece",
	1: "NewGeneration",
	2: "OwnerComplete",
}
var KeyStateCommand_KSMType_value = map[string]int32{
	"UpdateKeyPiece": 0,
	"NewGeneration":  1,
	"OwnerComplete":  2,
}

func (x KeyStateCommand_KSMType) String() string {
	return proto.EnumName(KeyStateCommand_KSMType_name, int32(x))
}
func (KeyStateCommand_KSMType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

type Configuration_ConfigurationType int32

const (
	Configuration_CurrentConfiguration Configuration_ConfigurationType = 0
	Configuration_FutureConfiguration  Configuration_ConfigurationType = 1
)

var Configuration_ConfigurationType_name = map[int32]string{
	0: "CurrentConfiguration",
	1: "FutureConfiguration",
}
var Configuration_ConfigurationType_value = map[string]int32{
	"CurrentConfiguration": 0,
	"FutureConfiguration":  1,
}

func (x Configuration_ConfigurationType) String() string {
	return proto.EnumName(Configuration_ConfigurationType_name, int32(x))
}
func (Configuration_ConfigurationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6, 0}
}

type Entry_EntryType int32

const (
	Entry_StateMachineCommand Entry_EntryType = 0
	Entry_ConfigurationChange Entry_EntryType = 1
	Entry_Demo                Entry_EntryType = 2
	Entry_KeyStateCommand     Entry_EntryType = 3
)

var Entry_EntryType_name = map[int32]string{
	0: "StateMachineCommand",
	1: "ConfigurationChange",
	2: "Demo",
	3: "KeyStateCommand",
}
var Entry_EntryType_value = map[string]int32{
	"StateMachineCommand": 0,
	"ConfigurationChange": 1,
	"Demo":                2,
	"KeyStateCommand":     3,
}

func (x Entry_EntryType) String() string {
	return proto.EnumName(Entry_EntryType_name, int32(x))
}
func (Entry_EntryType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{8, 0} }

type LeaderData_Type int32

const (
	LeaderData_State      LeaderData_Type = 0
	LeaderData_NodeChange LeaderData_Type = 1
	LeaderData_Event      LeaderData_Type = 2
)

var LeaderData_Type_name = map[int32]string{
	0: "State",
	1: "NodeChange",
	2: "Event",
}
var LeaderData_Type_value = map[string]int32{
	"State":      0,
	"NodeChange": 1,
	"Event":      2,
}

func (x LeaderData_Type) String() string {
	return proto.EnumName(LeaderData_Type_name, int32(x))
}
func (LeaderData_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{16, 0} }

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type EntryRequest struct {
	SenderId string `protobuf:"bytes,1,opt,name=sender_id,json=senderId" json:"sender_id,omitempty"`
	Entry    *Entry `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *EntryRequest) Reset()                    { *m = EntryRequest{} }
func (m *EntryRequest) String() string            { return proto.CompactTextString(m) }
func (*EntryRequest) ProtoMessage()               {}
func (*EntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *EntryRequest) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type AppendEntriesRequest struct {
	Term         uint64   `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderId     string   `protobuf:"bytes,2,opt,name=leader_id,json=leaderId" json:"leader_id,omitempty"`
	PrevLogIndex uint64   `protobuf:"varint,3,opt,name=prev_log_index,json=prevLogIndex" json:"prev_log_index,omitempty"`
	PrevLogTerm  uint64   `protobuf:"varint,4,opt,name=prev_log_term,json=prevLogTerm" json:"prev_log_term,omitempty"`
	Entries      []*Entry `protobuf:"bytes,5,rep,name=entries" json:"entries,omitempty"`
	LeaderCommit uint64   `protobuf:"varint,6,opt,name=leader_commit,json=leaderCommit" json:"leader_commit,omitempty"`
}

func (m *AppendEntriesRequest) Reset()                    { *m = AppendEntriesRequest{} }
func (m *AppendEntriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesRequest) ProtoMessage()               {}
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AppendEntriesRequest) GetEntries() []*Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

type StateMachineCommand struct {
	Type uint32 `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Path string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	// Used for Write command
	Data   []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Offset int64  `protobuf:"varint,4,opt,name=offset" json:"offset,omitempty"`
	// Used for Write and Truncate commands
	Length int64 `protobuf:"varint,5,opt,name=length" json:"length,omitempty"`
	// Used for Link and Rename commands
	OldPath string `protobuf:"bytes,6,opt,name=old_path,json=oldPath" json:"old_path,omitempty"`
	NewPath string `protobuf:"bytes,7,opt,name=new_path,json=newPath" json:"new_path,omitempty"`
	// Used for Create, Chmod and Mkdir commands
	Mode uint32 `protobuf:"varint,8,opt,name=mode" json:"mode,omitempty"`
	// Used for Utimes command
	AccessSeconds     int64 `protobuf:"varint,9,opt,name=access_seconds,json=accessSeconds" json:"access_seconds,omitempty"`
	AccessNanoseconds int64 `protobuf:"varint,10,opt,name=access_nanoseconds,json=accessNanoseconds" json:"access_nanoseconds,omitempty"`
	ModifySeconds     int64 `protobuf:"varint,11,opt,name=modify_seconds,json=modifySeconds" json:"modify_seconds,omitempty"`
	ModifyNanoseconds int64 `protobuf:"varint,12,opt,name=modify_nanoseconds,json=modifyNanoseconds" json:"modify_nanoseconds,omitempty"`
}

func (m *StateMachineCommand) Reset()                    { *m = StateMachineCommand{} }
func (m *StateMachineCommand) String() string            { return proto.CompactTextString(m) }
func (*StateMachineCommand) ProtoMessage()               {}
func (*StateMachineCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type KeyStateCommand struct {
	Type KeyStateCommand_KSMType `protobuf:"varint,1,opt,name=type,enum=raft.KeyStateCommand_KSMType" json:"type,omitempty"`
	// UpdateKeyPiece arguments
	KeyOwner   *Node `protobuf:"bytes,2,opt,name=key_owner,json=keyOwner" json:"key_owner,omitempty"`
	KeyHolder  *Node `protobuf:"bytes,3,opt,name=key_holder,json=keyHolder" json:"key_holder,omitempty"`
	Generation int64 `protobuf:"varint,4,opt,name=generation" json:"generation,omitempty"`
	// NewGeneration arguments
	NewNode string `protobuf:"bytes,5,opt,name=new_node,json=newNode" json:"new_node,omitempty"`
	// OwnerCompete arguments
	OwnerComplete string `protobuf:"bytes,6,opt,name=owner_complete,json=ownerComplete" json:"owner_complete,omitempty"`
}

func (m *KeyStateCommand) Reset()                    { *m = KeyStateCommand{} }
func (m *KeyStateCommand) String() string            { return proto.CompactTextString(m) }
func (*KeyStateCommand) ProtoMessage()               {}
func (*KeyStateCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KeyStateCommand) GetKeyOwner() *Node {
	if m != nil {
		return m.KeyOwner
	}
	return nil
}

func (m *KeyStateCommand) GetKeyHolder() *Node {
	if m != nil {
		return m.KeyHolder
	}
	return nil
}

type Node struct {
	Ip         string `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port       string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	CommonName string `protobuf:"bytes,3,opt,name=common_name,json=commonName" json:"common_name,omitempty"`
	NodeId     string `protobuf:"bytes,4,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Configuration struct {
	Type  Configuration_ConfigurationType `protobuf:"varint,1,opt,name=type,enum=raft.Configuration_ConfigurationType" json:"type,omitempty"`
	Nodes []*Node                         `protobuf:"bytes,2,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *Configuration) Reset()                    { *m = Configuration{} }
func (m *Configuration) String() string            { return proto.CompactTextString(m) }
func (*Configuration) ProtoMessage()               {}
func (*Configuration) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Configuration) GetNodes() []*Node {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type DemoCommand struct {
	Number uint64 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
}

func (m *DemoCommand) Reset()                    { *m = DemoCommand{} }
func (m *DemoCommand) String() string            { return proto.CompactTextString(m) }
func (*DemoCommand) ProtoMessage()               {}
func (*DemoCommand) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Entry struct {
	Type       Entry_EntryType      `protobuf:"varint,1,opt,name=type,enum=raft.Entry_EntryType" json:"type,omitempty"`
	Uuid       string               `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	Command    *StateMachineCommand `protobuf:"bytes,3,opt,name=command" json:"command,omitempty"`
	Config     *Configuration       `protobuf:"bytes,4,opt,name=config" json:"config,omitempty"`
	Demo       *DemoCommand         `protobuf:"bytes,5,opt,name=demo" json:"demo,omitempty"`
	KeyCommand *KeyStateCommand     `protobuf:"bytes,6,opt,name=key_command,json=keyCommand" json:"key_command,omitempty"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Entry) GetCommand() *StateMachineCommand {
	if m != nil {
		return m.Command
	}
	return nil
}

func (m *Entry) GetConfig() *Configuration {
	if m != nil {
		return m.Config
	}
	return nil
}

func (m *Entry) GetDemo() *DemoCommand {
	if m != nil {
		return m.Demo
	}
	return nil
}

func (m *Entry) GetKeyCommand() *KeyStateCommand {
	if m != nil {
		return m.KeyCommand
	}
	return nil
}

type LogEntry struct {
	Term  uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	Entry *Entry `protobuf:"bytes,2,opt,name=entry" json:"entry,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *LogEntry) GetEntry() *Entry {
	if m != nil {
		return m.Entry
	}
	return nil
}

type AppendEntriesResponse struct {
	Term      uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	NextIndex uint64 `protobuf:"varint,2,opt,name=next_index,json=nextIndex" json:"next_index,omitempty"`
	Success   bool   `protobuf:"varint,3,opt,name=success" json:"success,omitempty"`
}

func (m *AppendEntriesResponse) Reset()                    { *m = AppendEntriesResponse{} }
func (m *AppendEntriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AppendEntriesResponse) ProtoMessage()               {}
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type RequestVoteRequest struct {
	Term         uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	CandidateId  string `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId" json:"candidate_id,omitempty"`
	LastLogIndex uint64 `protobuf:"varint,3,opt,name=last_log_index,json=lastLogIndex" json:"last_log_index,omitempty"`
	LastLogTerm  uint64 `protobuf:"varint,4,opt,name=last_log_term,json=lastLogTerm" json:"last_log_term,omitempty"`
}

func (m *RequestVoteRequest) Reset()                    { *m = RequestVoteRequest{} }
func (m *RequestVoteRequest) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteRequest) ProtoMessage()               {}
func (*RequestVoteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type RequestVoteResponse struct {
	Term        uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	VoteGranted bool   `protobuf:"varint,2,opt,name=vote_granted,json=voteGranted" json:"vote_granted,omitempty"`
}

func (m *RequestVoteResponse) Reset()                    { *m = RequestVoteResponse{} }
func (m *RequestVoteResponse) String() string            { return proto.CompactTextString(m) }
func (*RequestVoteResponse) ProtoMessage()               {}
func (*RequestVoteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type SnapshotRequest struct {
	Term              uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
	LeaderId          string `protobuf:"bytes,2,opt,name=leader_id,json=leaderId" json:"leader_id,omitempty"`
	LastIncludedIndex uint64 `protobuf:"varint,3,opt,name=last_included_index,json=lastIncludedIndex" json:"last_included_index,omitempty"`
	LastIncludedTerm  uint64 `protobuf:"varint,4,opt,name=last_included_term,json=lastIncludedTerm" json:"last_included_term,omitempty"`
	Offset            uint64 `protobuf:"varint,5,opt,name=offset" json:"offset,omitempty"`
	Data              []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Done              bool   `protobuf:"varint,7,opt,name=done" json:"done,omitempty"`
}

func (m *SnapshotRequest) Reset()                    { *m = SnapshotRequest{} }
func (m *SnapshotRequest) String() string            { return proto.CompactTextString(m) }
func (*SnapshotRequest) ProtoMessage()               {}
func (*SnapshotRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type SnapshotResponse struct {
	Term uint64 `protobuf:"varint,1,opt,name=term" json:"term,omitempty"`
}

func (m *SnapshotResponse) Reset()                    { *m = SnapshotResponse{} }
func (m *SnapshotResponse) String() string            { return proto.CompactTextString(m) }
func (*SnapshotResponse) ProtoMessage()               {}
func (*SnapshotResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type LeaderDataRequest struct {
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId" json:"node_id,omitempty"`
}

func (m *LeaderDataRequest) Reset()                    { *m = LeaderDataRequest{} }
func (m *LeaderDataRequest) String() string            { return proto.CompactTextString(m) }
func (*LeaderDataRequest) ProtoMessage()               {}
func (*LeaderDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type LeaderData struct {
	Type LeaderData_Type  `protobuf:"varint,1,opt,name=type,enum=raft.LeaderData_Type" json:"type,omitempty"`
	Data *LeaderData_Data `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *LeaderData) Reset()                    { *m = LeaderData{} }
func (m *LeaderData) String() string            { return proto.CompactTextString(m) }
func (*LeaderData) ProtoMessage()               {}
func (*LeaderData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *LeaderData) GetData() *LeaderData_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type LeaderData_Data struct {
	Nodes  []*LeaderData_Data_DetailedNode `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
	Action string                          `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Node   *LeaderData_Data_DetailedNode   `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
	Event  *LeaderData_Data_Event          `protobuf:"bytes,4,opt,name=event" json:"event,omitempty"`
}

func (m *LeaderData_Data) Reset()                    { *m = LeaderData_Data{} }
func (m *LeaderData_Data) String() string            { return proto.CompactTextString(m) }
func (*LeaderData_Data) ProtoMessage()               {}
func (*LeaderData_Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16, 0} }

func (m *LeaderData_Data) GetNodes() []*LeaderData_Data_DetailedNode {
	if m != nil {
		return m.Nodes
	}
	return nil
}

func (m *LeaderData_Data) GetNode() *LeaderData_Data_DetailedNode {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *LeaderData_Data) GetEvent() *LeaderData_Data_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type LeaderData_Data_DetailedNode struct {
	Uuid       string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	CommonName string `protobuf:"bytes,2,opt,name=common_name,json=commonName" json:"common_name,omitempty"`
	Addr       string `protobuf:"bytes,3,opt,name=addr" json:"addr,omitempty"`
	State      string `protobuf:"bytes,4,opt,name=state" json:"state,omitempty"`
}

func (m *LeaderData_Data_DetailedNode) Reset()         { *m = LeaderData_Data_DetailedNode{} }
func (m *LeaderData_Data_DetailedNode) String() string { return proto.CompactTextString(m) }
func (*LeaderData_Data_DetailedNode) ProtoMessage()    {}
func (*LeaderData_Data_DetailedNode) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{16, 0, 0}
}

type LeaderData_Data_Event struct {
	Source  string `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Target  string `protobuf:"bytes,2,opt,name=target" json:"target,omitempty"`
	Details string `protobuf:"bytes,3,opt,name=details" json:"details,omitempty"`
}

func (m *LeaderData_Data_Event) Reset()                    { *m = LeaderData_Data_Event{} }
func (m *LeaderData_Data_Event) String() string            { return proto.CompactTextString(m) }
func (*LeaderData_Data_Event) ProtoMessage()               {}
func (*LeaderData_Data_Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16, 0, 1} }

func init() {
	proto.RegisterType((*EmptyMessage)(nil), "raft.EmptyMessage")
	proto.RegisterType((*EntryRequest)(nil), "raft.EntryRequest")
	proto.RegisterType((*AppendEntriesRequest)(nil), "raft.AppendEntriesRequest")
	proto.RegisterType((*StateMachineCommand)(nil), "raft.StateMachineCommand")
	proto.RegisterType((*KeyStateCommand)(nil), "raft.KeyStateCommand")
	proto.RegisterType((*Node)(nil), "raft.Node")
	proto.RegisterType((*Configuration)(nil), "raft.Configuration")
	proto.RegisterType((*DemoCommand)(nil), "raft.DemoCommand")
	proto.RegisterType((*Entry)(nil), "raft.Entry")
	proto.RegisterType((*LogEntry)(nil), "raft.LogEntry")
	proto.RegisterType((*AppendEntriesResponse)(nil), "raft.AppendEntriesResponse")
	proto.RegisterType((*RequestVoteRequest)(nil), "raft.RequestVoteRequest")
	proto.RegisterType((*RequestVoteResponse)(nil), "raft.RequestVoteResponse")
	proto.RegisterType((*SnapshotRequest)(nil), "raft.SnapshotRequest")
	proto.RegisterType((*SnapshotResponse)(nil), "raft.SnapshotResponse")
	proto.RegisterType((*LeaderDataRequest)(nil), "raft.LeaderDataRequest")
	proto.RegisterType((*LeaderData)(nil), "raft.LeaderData")
	proto.RegisterType((*LeaderData_Data)(nil), "raft.LeaderData.Data")
	proto.RegisterType((*LeaderData_Data_DetailedNode)(nil), "raft.LeaderData.Data.DetailedNode")
	proto.RegisterType((*LeaderData_Data_Event)(nil), "raft.LeaderData.Data.Event")
	proto.RegisterEnum("raft.KeyStateCommand_KSMType", KeyStateCommand_KSMType_name, KeyStateCommand_KSMType_value)
	proto.RegisterEnum("raft.Configuration_ConfigurationType", Configuration_ConfigurationType_name, Configuration_ConfigurationType_value)
	proto.RegisterEnum("raft.Entry_EntryType", Entry_EntryType_name, Entry_EntryType_value)
	proto.RegisterEnum("raft.LeaderData_Type", LeaderData_Type_name, LeaderData_Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for RaftNetwork service

type RaftNetworkClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	ClientToLeaderRequest(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EmptyMessage, error)
	InstallSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	RequestLeaderData(ctx context.Context, in *LeaderDataRequest, opts ...grpc.CallOption) (RaftNetwork_RequestLeaderDataClient, error)
}

type raftNetworkClient struct {
	cc *grpc.ClientConn
}

func NewRaftNetworkClient(cc *grpc.ClientConn) RaftNetworkClient {
	return &raftNetworkClient{cc}
}

func (c *raftNetworkClient) AppendEntries(ctx context.Context, in *AppendEntriesRequest, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	out := new(AppendEntriesResponse)
	err := grpc.Invoke(ctx, "/raft.RaftNetwork/AppendEntries", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNetworkClient) RequestVote(ctx context.Context, in *RequestVoteRequest, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	out := new(RequestVoteResponse)
	err := grpc.Invoke(ctx, "/raft.RaftNetwork/RequestVote", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNetworkClient) ClientToLeaderRequest(ctx context.Context, in *EntryRequest, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/raft.RaftNetwork/ClientToLeaderRequest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNetworkClient) InstallSnapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	out := new(SnapshotResponse)
	err := grpc.Invoke(ctx, "/raft.RaftNetwork/InstallSnapshot", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *raftNetworkClient) RequestLeaderData(ctx context.Context, in *LeaderDataRequest, opts ...grpc.CallOption) (RaftNetwork_RequestLeaderDataClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_RaftNetwork_serviceDesc.Streams[0], c.cc, "/raft.RaftNetwork/RequestLeaderData", opts...)
	if err != nil {
		return nil, err
	}
	x := &raftNetworkRequestLeaderDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RaftNetwork_RequestLeaderDataClient interface {
	Recv() (*LeaderData, error)
	grpc.ClientStream
}

type raftNetworkRequestLeaderDataClient struct {
	grpc.ClientStream
}

func (x *raftNetworkRequestLeaderDataClient) Recv() (*LeaderData, error) {
	m := new(LeaderData)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for RaftNetwork service

type RaftNetworkServer interface {
	AppendEntries(context.Context, *AppendEntriesRequest) (*AppendEntriesResponse, error)
	RequestVote(context.Context, *RequestVoteRequest) (*RequestVoteResponse, error)
	ClientToLeaderRequest(context.Context, *EntryRequest) (*EmptyMessage, error)
	InstallSnapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	RequestLeaderData(*LeaderDataRequest, RaftNetwork_RequestLeaderDataServer) error
}

func RegisterRaftNetworkServer(s *grpc.Server, srv RaftNetworkServer) {
	s.RegisterService(&_RaftNetwork_serviceDesc, srv)
}

func _RaftNetwork_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNetworkServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftNetwork/AppendEntries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNetworkServer).AppendEntries(ctx, req.(*AppendEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftNetwork_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNetworkServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftNetwork/RequestVote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNetworkServer).RequestVote(ctx, req.(*RequestVoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftNetwork_ClientToLeaderRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNetworkServer).ClientToLeaderRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftNetwork/ClientToLeaderRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNetworkServer).ClientToLeaderRequest(ctx, req.(*EntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftNetwork_InstallSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RaftNetworkServer).InstallSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/raft.RaftNetwork/InstallSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RaftNetworkServer).InstallSnapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RaftNetwork_RequestLeaderData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LeaderDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RaftNetworkServer).RequestLeaderData(m, &raftNetworkRequestLeaderDataServer{stream})
}

type RaftNetwork_RequestLeaderDataServer interface {
	Send(*LeaderData) error
	grpc.ServerStream
}

type raftNetworkRequestLeaderDataServer struct {
	grpc.ServerStream
}

func (x *raftNetworkRequestLeaderDataServer) Send(m *LeaderData) error {
	return x.ServerStream.SendMsg(m)
}

var _RaftNetwork_serviceDesc = grpc.ServiceDesc{
	ServiceName: "raft.RaftNetwork",
	HandlerType: (*RaftNetworkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _RaftNetwork_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _RaftNetwork_RequestVote_Handler,
		},
		{
			MethodName: "ClientToLeaderRequest",
			Handler:    _RaftNetwork_ClientToLeaderRequest_Handler,
		},
		{
			MethodName: "InstallSnapshot",
			Handler:    _RaftNetwork_InstallSnapshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RequestLeaderData",
			Handler:       _RaftNetwork_RequestLeaderData_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 1354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0x1b, 0xc5,
	0x17, 0x8f, 0xd7, 0xdf, 0xc7, 0xb1, 0x63, 0x4f, 0x9a, 0xd6, 0x75, 0xd5, 0xff, 0xbf, 0x5d, 0x28,
	0x50, 0x51, 0x02, 0xa4, 0x12, 0x82, 0xcb, 0xd6, 0xfd, 0x20, 0xb4, 0x75, 0xcb, 0xa6, 0x70, 0x85,
	0x64, 0x6d, 0xbd, 0x13, 0x67, 0x55, 0x7b, 0xd7, 0xec, 0x8e, 0x93, 0xe6, 0x01, 0x78, 0x04, 0x24,
	0x1e, 0x84, 0x7b, 0x9e, 0x04, 0x89, 0x1b, 0x6e, 0x78, 0x01, 0x6e, 0x39, 0x73, 0xce, 0xec, 0x7a,
	0xec, 0x2c, 0x55, 0xc5, 0x4d, 0x34, 0x73, 0xce, 0x6f, 0xcf, 0x9c, 0xcf, 0xdf, 0x89, 0x61, 0x27,
	0xf1, 0x8f, 0xd5, 0xa7, 0xfa, 0xcf, 0xfe, 0x22, 0x89, 0x55, 0x2c, 0x2a, 0xfa, 0xec, 0x76, 0x60,
	0xfb, 0xe1, 0x7c, 0xa1, 0xce, 0x9f, 0xc9, 0x34, 0xf5, 0xa7, 0xd2, 0x1d, 0xe1, 0x3d, 0x52, 0xc9,
	0xb9, 0x27, 0x7f, 0x5c, 0xca, 0x54, 0x89, 0x6b, 0xd0, 0x4c, 0x65, 0x14, 0xc8, 0x64, 0x1c, 0x06,
	0xfd, 0xd2, 0x8d, 0xd2, 0x47, 0x4d, 0xaf, 0xc1, 0x82, 0xc3, 0x40, 0xdc, 0x84, 0xaa, 0xd4, 0xe0,
	0xbe, 0x83, 0x8a, 0xd6, 0x41, 0x6b, 0x9f, 0xcc, 0xf3, 0xf7, 0xac, 0x71, 0x7f, 0x2f, 0xc1, 0xa5,
	0x7b, 0x8b, 0x05, 0x7e, 0xa1, 0xc5, 0xa1, 0x4c, 0x33, 0xc3, 0x02, 0x2a, 0x4a, 0x26, 0x73, 0xb2,
	0x59, 0xf1, 0xe8, 0xac, 0x1f, 0x9b, 0x49, 0xdf, 0x3c, 0xe6, 0xf0, 0x63, 0x2c, 0xc0, 0xc7, 0xde,
	0x87, 0xce, 0x22, 0x91, 0xa7, 0xe3, 0x59, 0x3c, 0x1d, 0x87, 0xe8, 0xc0, 0x9b, 0x7e, 0x99, 0x3e,
	0xdd, 0xd6, 0xd2, 0xa7, 0xf1, 0xf4, 0x50, 0xcb, 0x84, 0x0b, 0xed, 0x1c, 0x45, 0xf6, 0x2b, 0x04,
	0x6a, 0x19, 0xd0, 0x4b, 0xfd, 0xcc, 0x2d, 0xa8, 0x4b, 0x76, 0xa6, 0x5f, 0xbd, 0x51, 0xde, 0x74,
	0x3c, 0xd3, 0x89, 0xf7, 0xa0, 0x6d, 0xbc, 0x99, 0xc4, 0xf3, 0x79, 0xa8, 0xfa, 0x35, 0x7e, 0x8f,
	0x85, 0x43, 0x92, 0xb9, 0x7f, 0x3b, 0xb0, 0x7b, 0xa4, 0x7c, 0x25, 0x9f, 0xf9, 0x93, 0x93, 0x30,
	0x92, 0x5a, 0xec, 0x47, 0x01, 0x85, 0x77, 0xbe, 0x90, 0x14, 0x5e, 0xdb, 0xa3, 0xb3, 0x96, 0x2d,
	0x7c, 0x75, 0x62, 0x22, 0xa3, 0xb3, 0x96, 0x05, 0xbe, 0xf2, 0x29, 0x96, 0x6d, 0x8f, 0xce, 0xe2,
	0x32, 0xd4, 0xe2, 0xe3, 0xe3, 0x54, 0x2a, 0x72, 0xbe, 0xec, 0x99, 0x9b, 0x96, 0xcf, 0x64, 0x34,
	0x45, 0x0b, 0x55, 0x96, 0xf3, 0x4d, 0x5c, 0x85, 0x46, 0x3c, 0x0b, 0xc6, 0x64, 0xbb, 0x46, 0xb6,
	0xeb, 0x78, 0x7f, 0xe1, 0xb3, 0x2a, 0x92, 0x67, 0xac, 0xaa, 0xb3, 0x0a, 0xef, 0x2f, 0xcc, 0xcb,
	0xf3, 0x38, 0x90, 0xfd, 0x06, 0x7b, 0xa8, 0xcf, 0x98, 0x99, 0x8e, 0x3f, 0x99, 0x60, 0x2b, 0x8c,
	0x53, 0x39, 0x89, 0xa3, 0x20, 0xed, 0x37, 0xe9, 0xa5, 0x36, 0x4b, 0x8f, 0x58, 0x28, 0x3e, 0x01,
	0x61, 0x60, 0x91, 0x1f, 0xc5, 0x19, 0x14, 0x08, 0xda, 0x63, 0xcd, 0x68, 0xa5, 0xd0, 0x56, 0xd1,
	0x7a, 0x78, 0x7c, 0x9e, 0x5b, 0x6d, 0xb1, 0x55, 0x96, 0x5a, 0x56, 0x0d, 0xcc, 0xb6, 0xba, 0xcd,
	0x56, 0x59, 0x63, 0x59, 0x75, 0x7f, 0x73, 0x60, 0xe7, 0x89, 0x3c, 0xa7, 0xe4, 0x67, 0x59, 0xff,
	0xdc, 0xca, 0x7a, 0xe7, 0xe0, 0x3a, 0x97, 0x75, 0x03, 0xb4, 0xff, 0xe4, 0xe8, 0xd9, 0x4b, 0x04,
	0x99, 0xa2, 0x7c, 0x08, 0xcd, 0xd7, 0xf2, 0x7c, 0x1c, 0x9f, 0x45, 0x32, 0x31, 0x7d, 0x0c, 0xfc,
	0xdd, 0x08, 0x33, 0xe2, 0x35, 0x50, 0xf9, 0x5c, 0xeb, 0xc4, 0x6d, 0x00, 0x0d, 0x3c, 0xc1, 0xd4,
	0x22, 0xb2, 0x7c, 0x01, 0xa9, 0xcd, 0x7c, 0x4d, 0x4a, 0xf1, 0x3f, 0x80, 0xa9, 0xc4, 0x6f, 0x7c,
	0x15, 0xc6, 0x91, 0x29, 0xa2, 0x25, 0xc9, 0xaa, 0x12, 0xe9, 0xf4, 0x57, 0xf3, 0xaa, 0x8c, 0x4c,
	0x05, 0xc8, 0x15, 0xdd, 0x73, 0x8b, 0x99, 0x54, 0xd2, 0x54, 0xb4, 0x4d, 0xd2, 0xa1, 0x11, 0xba,
	0x43, 0xa8, 0x9b, 0x30, 0xb0, 0x8e, 0x9d, 0xef, 0x16, 0xd8, 0x37, 0x12, 0xe3, 0x7c, 0x11, 0xca,
	0x89, 0xec, 0x6e, 0x89, 0x1e, 0xb4, 0x47, 0xf2, 0xec, 0x71, 0xfe, 0x62, 0xb7, 0xa4, 0x45, 0xcf,
	0x6d, 0x13, 0x5d, 0xc7, 0x0d, 0xa0, 0x42, 0x6f, 0x76, 0xc0, 0x09, 0x17, 0x66, 0xb8, 0xf1, 0x44,
	0x7d, 0x1a, 0x27, 0x2a, 0xef, 0x53, 0x3c, 0x8b, 0xff, 0x43, 0x4b, 0x4f, 0x41, 0x1c, 0x61, 0x71,
	0xe6, 0x92, 0xc2, 0x6f, 0x7a, 0xc0, 0xa2, 0x11, 0x4a, 0xc4, 0x15, 0xa8, 0xeb, 0x78, 0xf4, 0xe4,
	0x56, 0x48, 0x59, 0xd3, 0xd7, 0xc3, 0xc0, 0xfd, 0xb5, 0x04, 0xed, 0x61, 0x1c, 0x1d, 0x87, 0xd3,
	0xa5, 0x09, 0xff, 0xab, 0xb5, 0x2a, 0xdd, 0xe2, 0x1c, 0xae, 0x41, 0xd6, 0x6f, 0x56, 0xb5, 0x6e,
	0x40, 0x55, 0x9b, 0x4d, 0xd1, 0xb7, 0xf2, 0x46, 0xfe, 0x59, 0xe1, 0x3e, 0x82, 0xde, 0x85, 0x8f,
	0x45, 0x1f, 0x2e, 0x0d, 0x97, 0x49, 0x82, 0x93, 0xbd, 0xa6, 0xc3, 0x4c, 0x5d, 0x81, 0xdd, 0x47,
	0x4b, 0xb5, 0x4c, 0xe4, 0xba, 0xa2, 0xe4, 0xde, 0x82, 0xd6, 0x03, 0x39, 0x8f, 0xb3, 0xce, 0xc2,
	0xd9, 0x8b, 0x96, 0xf3, 0x57, 0x58, 0x79, 0x26, 0x2c, 0x73, 0x73, 0xff, 0x74, 0xa0, 0x4a, 0xbc,
	0x81, 0xfd, 0x61, 0x47, 0xb5, 0x67, 0x51, 0x0a, 0xff, 0xb5, 0xa2, 0xc0, 0x04, 0x2f, 0x97, 0x39,
	0xc5, 0xd1, 0x59, 0xdc, 0x85, 0xfa, 0x84, 0xdf, 0x32, 0xbd, 0x75, 0x95, 0x2d, 0x14, 0x90, 0x8b,
	0x97, 0x21, 0xc5, 0xc7, 0x50, 0x9b, 0x90, 0xdf, 0x94, 0xf3, 0xd6, 0xc1, 0x6e, 0x41, 0x2e, 0x3d,
	0x03, 0xc1, 0xd6, 0xaa, 0x04, 0x18, 0x11, 0x75, 0x5c, 0xeb, 0xa0, 0xc7, 0x50, 0x2b, 0x46, 0x8f,
	0xd4, 0xe2, 0x0b, 0x68, 0xe9, 0x3e, 0xcf, 0x9c, 0xa9, 0x11, 0x7a, 0xaf, 0x70, 0x94, 0x3c, 0x3d,
	0x11, 0xe6, 0xec, 0xfe, 0x00, 0xcd, 0x3c, 0x4e, 0x9d, 0xd6, 0x02, 0xc7, 0x39, 0xdf, 0x6b, 0xde,
	0x0d, 0x4f, 0xfc, 0x68, 0x2a, 0xb1, 0x3f, 0x1b, 0x50, 0xd1, 0xbe, 0x74, 0x1d, 0xb1, 0x7b, 0x61,
	0xae, 0xbb, 0x65, 0xf7, 0x1e, 0x34, 0x90, 0xbe, 0x39, 0xd3, 0x45, 0xab, 0xe3, 0x1d, 0x56, 0x51,
	0x00, 0x7b, 0x1b, 0x9b, 0x28, 0x5d, 0xc4, 0x51, 0x2a, 0x0b, 0xed, 0x5d, 0x07, 0x88, 0xe4, 0x1b,
	0x65, 0x36, 0x8d, 0x43, 0x9a, 0xa6, 0x96, 0xf0, 0x9a, 0xe9, 0x43, 0x3d, 0x5d, 0x12, 0xd1, 0x51,
	0xb5, 0x1a, 0x5e, 0x76, 0x75, 0x7f, 0x2e, 0x81, 0x30, 0x3b, 0xee, 0xfb, 0x58, 0xc9, 0xb7, 0xad,
	0xbb, 0x9b, 0xb0, 0x3d, 0xc1, 0xe8, 0x42, 0x3d, 0xbc, 0xab, 0x8d, 0xd7, 0xca, 0x65, 0xbc, 0xf4,
	0x66, 0x7e, 0xaa, 0x2e, 0x2e, 0x3d, 0x2d, 0xb5, 0x97, 0x5e, 0x8e, 0xb2, 0x97, 0x9e, 0x01, 0xe9,
	0xa5, 0xe7, 0x3e, 0x85, 0xdd, 0x35, 0xb7, 0xde, 0x12, 0x3b, 0xfa, 0x75, 0x8a, 0x98, 0xf1, 0x34,
	0xf1, 0x23, 0x25, 0xd9, 0xaf, 0x86, 0xd7, 0xd2, 0xb2, 0xc7, 0x2c, 0x72, 0xff, 0x28, 0xc1, 0xce,
	0x51, 0xe4, 0x2f, 0xd2, 0x93, 0x58, 0xfd, 0xe7, 0x8d, 0xbe, 0x0f, 0xbb, 0xe4, 0x76, 0x18, 0x4d,
	0x66, 0xcb, 0x40, 0x06, 0x6b, 0x11, 0xf6, 0xb4, 0xea, 0xd0, 0x68, 0x38, 0xcc, 0x3b, 0x20, 0xd6,
	0xf1, 0x56, 0xac, 0x5d, 0x1b, 0x4e, 0x5b, 0x7e, 0xb5, 0x45, 0xab, 0x3c, 0xb1, 0x66, 0x8b, 0x66,
	0x1b, 0xb7, 0x66, 0x6d, 0x5c, 0x2d, 0x8b, 0x23, 0x49, 0x2b, 0xb2, 0xe1, 0xd1, 0xd9, 0xfd, 0x00,
	0xba, 0xab, 0x08, 0xff, 0x3d, 0x5b, 0xee, 0x1d, 0xe8, 0x3d, 0xa5, 0x88, 0x1e, 0xa0, 0xa5, 0x2c,
	0x17, 0x16, 0x1b, 0x96, 0xd6, 0xd8, 0xf0, 0x97, 0x0a, 0xc0, 0x0a, 0x5e, 0x4c, 0x1a, 0x2b, 0xfd,
	0xbe, 0x45, 0x1a, 0xb7, 0x8d, 0xdf, 0x8e, 0x3d, 0x90, 0x16, 0x94, 0x9e, 0x27, 0xc8, 0xe0, 0xa7,
	0x32, 0x0e, 0x93, 0x36, 0xff, 0x65, 0x46, 0x97, 0x25, 0xa2, 0x4b, 0xb7, 0xf0, 0x23, 0xe4, 0x00,
	0xe5, 0x87, 0x33, 0x19, 0x58, 0x34, 0xaa, 0xb3, 0xe7, 0x4f, 0x68, 0x7d, 0x71, 0xd5, 0xcc, 0x0d,
	0xd9, 0xa1, 0x42, 0x6b, 0x8b, 0x39, 0xea, 0x5d, 0x0c, 0x12, 0x1e, 0x37, 0x73, 0x55, 0x9e, 0xe2,
	0x1c, 0x1a, 0xa2, 0xba, 0x56, 0xfc, 0xe1, 0x43, 0x0d, 0xf1, 0x18, 0x39, 0x98, 0xc3, 0xb6, 0x6d,
	0x28, 0x67, 0xcd, 0x92, 0xc5, 0x9a, 0x1b, 0x6b, 0xc9, 0xb9, 0xb0, 0x96, 0xf0, 0x23, 0x3f, 0x08,
	0x12, 0xb3, 0xb0, 0xe8, 0x2c, 0x2e, 0x41, 0x35, 0xd5, 0xec, 0x62, 0x16, 0x15, 0x5f, 0x06, 0xdf,
	0x22, 0x91, 0xeb, 0x77, 0x75, 0xe8, 0x69, 0xbc, 0x4c, 0x26, 0x32, 0x2b, 0x1d, 0xdf, 0xb4, 0x5c,
	0xf9, 0xc9, 0x54, 0x66, 0x8b, 0xd1, 0xdc, 0x34, 0x17, 0x04, 0xe4, 0x67, 0x6a, 0x5e, 0xc9, 0xae,
	0xd8, 0x1a, 0x15, 0x62, 0xc3, 0x26, 0x54, 0x89, 0xce, 0x90, 0xff, 0x3a, 0x00, 0x3a, 0x98, 0x9c,
	0xf6, 0x9a, 0xe6, 0xd5, 0xae, 0x73, 0xf0, 0x97, 0x03, 0x2d, 0x0f, 0xb3, 0x32, 0x92, 0xea, 0x2c,
	0x4e, 0x5e, 0x8b, 0x6f, 0xa0, 0xbd, 0xc6, 0x57, 0x62, 0xc0, 0x49, 0x2b, 0xfa, 0x77, 0x7a, 0x70,
	0xad, 0x50, 0xc7, 0x6d, 0xeb, 0x6e, 0x89, 0x07, 0x68, 0x7a, 0x35, 0xfd, 0xa2, 0xcf, 0xe8, 0x8b,
	0x3c, 0x35, 0xb8, 0x5a, 0xa0, 0xc9, 0xad, 0xdc, 0x83, 0xbd, 0xe1, 0x2c, 0x44, 0x6f, 0x5f, 0xc6,
	0x5c, 0xb9, 0x7c, 0xf4, 0x6d, 0xba, 0x35, 0x96, 0x32, 0x99, 0xfd, 0xeb, 0x62, 0x4b, 0xdc, 0x87,
	0x9d, 0xc3, 0x08, 0x13, 0x3e, 0x9b, 0x65, 0xc3, 0x25, 0x4c, 0x2b, 0x6f, 0xd0, 0xc9, 0xe0, 0xf2,
	0xa6, 0x38, 0x77, 0xe3, 0x3e, 0xf4, 0x0c, 0xc8, 0x9a, 0xa4, 0x2b, 0x9b, 0x1d, 0x95, 0xd9, 0xe9,
	0x6e, 0x2a, 0xdc, 0xad, 0xcf, 0x4a, 0xaf, 0x6a, 0xf4, 0x23, 0xe8, 0xee, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xf8, 0x08, 0xc4, 0x54, 0x17, 0x0d, 0x00, 0x00,
}
